/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.clsRacionales;
import Entidades.ClsFracciones;
import javax.swing.JOptionPane;

/**
 *
 * @author Programacion
 */
public class frmMultiplicaFracciones extends javax.swing.JFrame {

    /**
     * Creates new form frmMultiplicaFracciones
     */
    public frmMultiplicaFracciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeradorRes2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtNumerador1 = new javax.swing.JTextField();
        txtDenominador1 = new javax.swing.JTextField();
        txtNumerador2 = new javax.swing.JTextField();
        txtDenominador2 = new javax.swing.JTextField();
        cmbOperacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIgual = new javax.swing.JButton();
        txtDenominadorRes = new javax.swing.JTextField();
        txtNumeradorRes = new javax.swing.JTextField();
        txtdecimalRes2 = new javax.swing.JTextField();
        txtFracRes3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        txtNumeradorRes2.setEditable(false);
        txtNumeradorRes2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNumeradorRes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeradorRes2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operación de Fracciones");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Algrebra de Fracciones"));

        txtNumerador1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNumerador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerador1KeyTyped(evt);
            }
        });

        txtDenominador1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDenominador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDenominador1KeyTyped(evt);
            }
        });

        txtNumerador2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNumerador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerador2KeyTyped(evt);
            }
        });

        txtDenominador2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDenominador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDenominador2KeyTyped(evt);
            }
        });

        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "×", "÷" }));

        jLabel1.setText("Numerador:");

        jLabel2.setText("Denominador:");

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        txtDenominadorRes.setEditable(false);
        txtDenominadorRes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtNumeradorRes.setEditable(false);
        txtNumeradorRes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtdecimalRes2.setEditable(false);
        txtdecimalRes2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtFracRes3.setEditable(false);
        txtFracRes3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setText("=");

        jLabel4.setText("=");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(txtDenominador1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txtNumerador1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumerador2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDenominador2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIgual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeradorRes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDenominadorRes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtdecimalRes2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFracRes3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumerador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNumerador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDenominador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtDenominador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNumeradorRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(txtDenominadorRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(cmbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnIgual))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdecimalRes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFracRes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeradorRes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeradorRes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeradorRes2ActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        //Variables
        clsRacionales vlo_Operaciones = new clsRacionales();
        ClsFracciones vlo_PrimerFraccion;
        ClsFracciones vlo_SegundaFraccion;
        ClsFracciones vlo_ResultadoFraccion;
        ClsFracciones vlo_TamporalRes = new ClsFracciones();

        //Inicio
        if (txtDenominador2.getText().equals("0") || txtDenominador1.getText().equals("0")) {
            JOptionPane.showInputDialog(this, "Error una indefinición matematica.");
        } else {
            if (txtNumerador1.getText().equals("") || txtNumerador2.getText().equals("")) {
                JOptionPane.showInputDialog(this, "Algún campo requerido se encuentra vacio.");
            } else {
                try {
                    //Se verifica si se dejó en blanco el campo de los denominadores.
                    if (txtDenominador2.getText().equals("")) {
                        txtDenominador2.setText("1");
                    }
                    if (txtDenominador1.getText().equals("")) {
                        txtDenominador1.setText("1");
                    }

                    //Se guarda los valores en las variables objetos.
                    vlo_PrimerFraccion = new ClsFracciones(Integer.parseInt(txtNumerador1.getText()), Integer.parseInt(txtDenominador1.getText()));
                    if (cmbOperacion.getSelectedItem().equals("÷")) {
                        vlo_SegundaFraccion = new ClsFracciones(Integer.parseInt(txtDenominador2.getText()), Integer.parseInt(txtNumerador2.getText()));
                    } else {
                        vlo_SegundaFraccion = new ClsFracciones(Integer.parseInt(txtNumerador2.getText()), Integer.parseInt(txtDenominador2.getText()));
                    }

                    //Se verifica que tipo de oprerador se está utilizando.
                    if (cmbOperacion.getSelectedItem().equals("-")) {
                        vlo_Operaciones.setVgn_PrimerFraccion(vlo_PrimerFraccion);
                        vlo_SegundaFraccion.setVgn_Numerador(-vlo_SegundaFraccion.getVgn_Numerador());
                        vlo_Operaciones.setVgn_SegundaFraccion(vlo_SegundaFraccion);
                        vlo_Operaciones.SumaFracciones();
                        vlo_TamporalRes = vlo_Operaciones.getVgn_ResultadoFracciones();
                        vlo_ResultadoFraccion = new ClsFracciones(vlo_TamporalRes.getVgn_Numerador(), vlo_TamporalRes.getVgn_Denominador());
                        if (vlo_ResultadoFraccion.getVgn_Denominador() == vlo_ResultadoFraccion.getVgn_Numerador()) {
                            txtNumeradorRes.setText("1");
                        } else {
                            if (vlo_ResultadoFraccion.getVgn_Denominador() == 1) {
                                txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                            } else {
                                if (vlo_ResultadoFraccion.getVgn_Numerador() == 0) {
                                    txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                                } else {
                                    txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                                    txtDenominadorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Denominador()));
                                }
                            }
                        }
                        txtdecimalRes2.setText(vlo_Operaciones.PuntoFlotante(vlo_ResultadoFraccion.getVgn_Numerador(), vlo_ResultadoFraccion.getVgn_Denominador()));
                        txtFracRes3.setText(vlo_Operaciones.FraccionLinea(vlo_ResultadoFraccion.getVgn_Numerador(), vlo_ResultadoFraccion.getVgn_Denominador()));
                    } else if (cmbOperacion.getSelectedItem().equals("+")) {
                        vlo_Operaciones.setVgn_PrimerFraccion(vlo_PrimerFraccion);
                        vlo_SegundaFraccion.setVgn_Numerador(vlo_SegundaFraccion.getVgn_Numerador());
                        vlo_Operaciones.setVgn_SegundaFraccion(vlo_SegundaFraccion);
                        vlo_Operaciones.SumaFracciones();
                        vlo_TamporalRes = vlo_Operaciones.getVgn_ResultadoFracciones();
                        vlo_ResultadoFraccion = new ClsFracciones(vlo_TamporalRes.getVgn_Numerador(), vlo_TamporalRes.getVgn_Denominador());
                        if (vlo_ResultadoFraccion.getVgn_Denominador() == vlo_ResultadoFraccion.getVgn_Numerador()) {
                            txtNumeradorRes.setText("1");
                        } else {
                            if (vlo_ResultadoFraccion.getVgn_Denominador() == 1) {
                                txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                            } else {
                                if (vlo_ResultadoFraccion.getVgn_Numerador() == 0) {
                                    txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                                } else {
                                    txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                                    txtDenominadorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Denominador()));
                                }
                            }
                        }
                        txtdecimalRes2.setText(vlo_Operaciones.PuntoFlotante(vlo_ResultadoFraccion.getVgn_Numerador(), vlo_ResultadoFraccion.getVgn_Denominador()));
                        txtFracRes3.setText(vlo_Operaciones.FraccionLinea(vlo_ResultadoFraccion.getVgn_Numerador(), vlo_ResultadoFraccion.getVgn_Denominador()));
                    } else if (cmbOperacion.getSelectedItem().equals("÷")) {
                        vlo_Operaciones.setVgn_PrimerFraccion(vlo_PrimerFraccion);
                        vlo_SegundaFraccion.setVgn_Numerador(vlo_SegundaFraccion.getVgn_Numerador());
                        vlo_Operaciones.setVgn_SegundaFraccion(vlo_SegundaFraccion);
                        vlo_Operaciones.MultiplicarFracciones();
                        vlo_TamporalRes = vlo_Operaciones.getVgn_ResultadoFracciones();
                        vlo_ResultadoFraccion = new ClsFracciones(vlo_TamporalRes.getVgn_Numerador(), vlo_TamporalRes.getVgn_Denominador());
                        if (vlo_ResultadoFraccion.getVgn_Denominador() == vlo_ResultadoFraccion.getVgn_Numerador()) {
                            txtNumeradorRes.setText("1");
                        } else {
                            if (vlo_ResultadoFraccion.getVgn_Denominador() == 1) {
                                txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                            } else {
                                if (vlo_ResultadoFraccion.getVgn_Numerador() == 0) {
                                    txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                                } else {
                                    txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                                    txtDenominadorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Denominador()));
                                }
                            }
                        }
                        txtdecimalRes2.setText(vlo_Operaciones.PuntoFlotante(vlo_ResultadoFraccion.getVgn_Numerador(), vlo_ResultadoFraccion.getVgn_Denominador()));
                        txtFracRes3.setText(vlo_Operaciones.FraccionLinea(vlo_ResultadoFraccion.getVgn_Numerador(), vlo_ResultadoFraccion.getVgn_Denominador()));
                    } else if (cmbOperacion.getSelectedItem().equals("×")) {
                        vlo_Operaciones.setVgn_PrimerFraccion(vlo_PrimerFraccion);
                        vlo_SegundaFraccion.setVgn_Numerador(vlo_SegundaFraccion.getVgn_Numerador());
                        vlo_Operaciones.setVgn_SegundaFraccion(vlo_SegundaFraccion);
                        vlo_Operaciones.MultiplicarFracciones();
                        vlo_TamporalRes = vlo_Operaciones.getVgn_ResultadoFracciones();
                        vlo_ResultadoFraccion = new ClsFracciones(vlo_TamporalRes.getVgn_Numerador(), vlo_TamporalRes.getVgn_Denominador());
                        if (vlo_ResultadoFraccion.getVgn_Denominador() == vlo_ResultadoFraccion.getVgn_Numerador()) {
                            txtNumeradorRes.setText("1");
                        } else {
                            if (vlo_ResultadoFraccion.getVgn_Denominador() == 1) {
                                txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                            } else {
                                if (vlo_ResultadoFraccion.getVgn_Numerador() == 0) {
                                    txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                                } else {
                                    txtNumeradorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Numerador()));
                                    txtDenominadorRes.setText(Integer.toString(vlo_ResultadoFraccion.getVgn_Denominador()));
                                }
                            }
                        }
                        txtdecimalRes2.setText(vlo_Operaciones.PuntoFlotante(vlo_ResultadoFraccion.getVgn_Numerador(), vlo_ResultadoFraccion.getVgn_Denominador()));
                        txtFracRes3.setText(vlo_Operaciones.FraccionLinea(vlo_ResultadoFraccion.getVgn_Numerador(), vlo_ResultadoFraccion.getVgn_Denominador()));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar número es incorrecto.");
                }
            }
        }

    }//GEN-LAST:event_btnIgualActionPerformed

    private void txtNumerador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerador1KeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumerador1KeyTyped

    private void txtDenominador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominador1KeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtDenominador1KeyTyped

    private void txtNumerador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerador2KeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumerador2KeyTyped

    private void txtDenominador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominador2KeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtDenominador2KeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtDenominador1.setText("");
        txtDenominador2.setText("");
        txtDenominadorRes.setText("");
        txtFracRes3.setText("");
        txtNumerador1.setText("");
        txtNumerador2.setText("");
        txtNumeradorRes.setText("");
        txtNumeradorRes2.setText("");
        txtdecimalRes2.setText("");
        cmbOperacion.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMultiplicaFracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMultiplicaFracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMultiplicaFracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMultiplicaFracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMultiplicaFracciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDenominador1;
    private javax.swing.JTextField txtDenominador2;
    private javax.swing.JTextField txtDenominadorRes;
    private javax.swing.JTextField txtFracRes3;
    private javax.swing.JTextField txtNumerador1;
    private javax.swing.JTextField txtNumerador2;
    private javax.swing.JTextField txtNumeradorRes;
    private javax.swing.JTextField txtNumeradorRes2;
    private javax.swing.JTextField txtdecimalRes2;
    // End of variables declaration//GEN-END:variables
}
