/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidades.ClsEntidadCliente;
import Logica.LogicaClientes;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thomas
 */
public class frmClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmClientes
     */
    boolean RegistroNuevo;
    ClsEntidadCliente EntidadRegistrada = null;

    public frmClientes() {
        initComponents();
        this.closable = true;
        RegistroNuevo = true;
        try {
            CargarListaClientes();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txt_NombreCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_DireccionCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_TelefonoCliente = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Guardar Cliente"));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Dirección:");

        jLabel4.setText("Teléfono:");

        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomas\\Documents\\GitHub\\MODULO_5_2019\\Ejemplo\\EjemploCapas\\rcs\\guardar.png")); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_NombreCliente)
                            .addComponent(txt_DireccionCliente)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar))
                            .addComponent(txt_TelefonoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_DireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(txt_TelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))))
        );

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
//        //Variables
//        ClsEntidadCliente vlo_Cliente = new ClsEntidadCliente();
//        LogicaClientes vlo_LogicaClientes = new LogicaClientes();
//        int vln_Resultado = 0;
//
//        //Inicio
//        try {
//            vlo_Cliente = LeerDatos();
//            vln_Resultado = vlo_LogicaClientes.InsertarCliente(vlo_Cliente);
//            if (vln_Resultado > 0) {
//                JOptionPane.showMessageDialog(this, "Cliente guardado de forma satisfactoria.");
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Error al guardar el cliente");
//        }
        GuardarCliente();
        try {
            CargarListaClientes();
        } catch (Exception ex) {
            Logger.getLogger(frmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Varaibles
        int vln_idCliente;
        try {
            if (!txt_id.getText().equals("")) {
                vln_idCliente = Integer.parseInt(txt_id.getText());
                CargarDatos(vln_idCliente);
            } else {
                JOptionPane.showMessageDialog(this, "debe insertar in codigo para buscar.");
                Limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            EliminarCliente();
            CargarListaClientes();
        } catch (Exception ex) {
            Logger.getLogger(frmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Limpiar() {
        txt_DireccionCliente.setText("");
        txt_NombreCliente.setText("");
        txt_TelefonoCliente.setText("");
        txt_id.setText("");
        RegistroNuevo = true;
    }

    private ClsEntidadCliente LeerDatos() {
        //Varaibles
        ClsEntidadCliente vlo_Cliente;
        try {
            vlo_Cliente = new ClsEntidadCliente();
//            if (txt_NombreCliente.getName().equals(null)) {
//                txt_NombreCliente.setName("-1");
//            }
            vlo_Cliente.setVgc_Nombre(txt_NombreCliente.getText());
            vlo_Cliente.setVgc_Telefono(txt_TelefonoCliente.getText());
            vlo_Cliente.setVgc_Direccion(txt_TelefonoCliente.getText());
            vlo_Cliente.setVgn_idCliente(/*Integer.parseInt(txt_NombreCliente.getName())*/-1);
        } catch (Exception e) {
            throw e;
        }
        return vlo_Cliente;
    }

    private void CargarListaClientes() throws Exception {
        ResultSet vlo_dsDatos;
        LogicaClientes vlo_logiLogicaClientes = new LogicaClientes();
        DefaultTableModel modelo = new DefaultTableModel();
        tblClientes.setModel(modelo);
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Dirección");
        modelo.addColumn("Teléfono");
        try {
            vlo_dsDatos = vlo_logiLogicaClientes.ListaClientes("", "");
            //Se crea un array que será una de las filaos dela tabla.
            Object[] fila = new Object[4];
            while (vlo_dsDatos.next()) {
                for (int i = 0; i < 4; i++) {
                    fila[i] = vlo_dsDatos.getObject(i + 1);
                }
                modelo.addRow(fila);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, vlo_logiLogicaClientes.getVln_msj());
        }
    }

    private ClsEntidadCliente GenerarCliente() {
        //Varaibles
        ClsEntidadCliente vlo_Cliente;

        try {
            if (RegistroNuevo = true) {
                vlo_Cliente = new ClsEntidadCliente();
            } else {
                vlo_Cliente = EntidadRegistrada;
            }
            vlo_Cliente.setVgc_Nombre(txt_NombreCliente.getText());
            vlo_Cliente.setVgc_Telefono(txt_TelefonoCliente.getText());
            vlo_Cliente.setVgc_Direccion(txt_DireccionCliente.getText());
        } catch (Exception e) {
            throw e;
        }
        return vlo_Cliente;
    }

    private int GuardarCliente() {
        //Varaibles
        ClsEntidadCliente vlo_Cliente;
        LogicaClientes vlo_Logica = new LogicaClientes();
        int vln_Resultado = 0;

        try {
            vlo_Cliente = GenerarCliente();
            vln_Resultado = vlo_Logica.InsertarCliente(vlo_Cliente);

            if (vln_Resultado > 0) {
                JOptionPane.showMessageDialog(this, "Operación realizada de forma satisfactoria.");
            } else {
                JOptionPane.showMessageDialog(this, "No se guardó el cliente.");
            }
        } catch (Exception e) {
            throw e;
        }
        return vln_Resultado;
    }

    private void CargarDatos(int pvn_IDCliente) throws Exception {
        //varaibles
        LogicaClientes vlo_LogicaClientes = new LogicaClientes();
        ClsEntidadCliente vlo_EntidadCliente;
        String vlc_condicion;
        try {
            vlc_condicion = String.format("ID_CLIENTE = %s", String.valueOf(pvn_IDCliente));
            vlo_EntidadCliente = vlo_LogicaClientes.ObtenerCliente(vlc_condicion);
            if (vlo_EntidadCliente.isVgb_ExisteRegistro()) {
                txt_id.setText(String.valueOf(vlo_EntidadCliente.getVgn_idCliente()));
                txt_DireccionCliente.setText(String.valueOf(vlo_EntidadCliente.getVgc_Direccion()));
                txt_NombreCliente.setText(String.valueOf(vlo_EntidadCliente.getVgc_Nombre()));
                txt_TelefonoCliente.setText(String.valueOf(vlo_EntidadCliente.getVgc_Telefono()));

                EntidadRegistrada = vlo_EntidadCliente;
                RegistroNuevo = false;
            } else {
                JOptionPane.showMessageDialog(this, "El cliente no existe.");
            }
        } catch (Exception e) {
            throw e;
        }
    }

    private int EliminarCliente() throws Exception {
        //Variables
        int vln_resultado = -1;
        LogicaClientes vlo_LogicaClientes = new LogicaClientes();

        //Inicio
        try {
            if (!txt_id.getText().equals("") && (!RegistroNuevo)) {
                vln_resultado = vlo_LogicaClientes.EliminarCliente(EntidadRegistrada);
                JOptionPane.showMessageDialog(this, "Operación realizada de froma satisfatoria.");
                Limpiar();
                CargarListaClientes();
            } else {
                JOptionPane.showInternalMessageDialog(this, "Debe introducir el código delicliente.");
            }
        } catch (Exception e) {
            throw e;
        }
        return vln_resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txt_DireccionCliente;
    private javax.swing.JTextField txt_NombreCliente;
    private javax.swing.JTextField txt_TelefonoCliente;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
