/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidades.ClsEntidaProducto;
import Entidades.ClsEntidadRetorno;
import Logica.LogicaProducto;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tomas
 */
public class frmProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmProductos
     */
    public frmProductos() {
        initComponents();
        txt_idProducto.setVisible(false);
        Limpiar();
        this.closable = true;
        CargarListaProductos();
    }

    private void Limpiar() {
        txt_Buscar.setText("");
        txt_DetalleProducto.setText("");
        txt_PrecioProducto.setText("");
        txt_idProducto.setText("-1");
    }

    private void CargarListaProductos() {
        //Variables
        ResultSet vlo_RS;
        LogicaProducto vlo_loLogicaProducto = new LogicaProducto();
        DefaultTableModel Modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;

            }
        };
        //DefaultTableModel modelo = new DefaultTableModel();

        //Inicio
        jTable1.setModel(Modelo);
        Modelo.addColumn("Código");
        Modelo.addColumn("Detalle");
        Modelo.addColumn("Precio");

        try {
            vlo_RS = vlo_loLogicaProducto.ListaProductos(txt_Buscar.getText());
            Object[] fila = new Object[3];
            while (vlo_RS.next()) {
                for (int i = 0; i < 3; i++) {
                    fila[i] = vlo_RS.getObject(i + 1);
                }
                Modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los productos.");
        }
    }

    private ClsEntidaProducto LeerDatos() {
        //Variables
        ClsEntidaProducto vlo_Producto = new ClsEntidaProducto();

        //Inicio
        //Se verifica si los campos no se en cuentran vacios.
        if (txt_DetalleProducto.getText().equals("") || txt_PrecioProducto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Error el producto debe tener un detalle y un precio.");
        } else {
            //se verifica si la cantidad de caracyteres es correcta.
            if (txt_DetalleProducto.getText().length() > 30) {
                JOptionPane.showMessageDialog(this, "Error el detalle de producto no puede tener más de 30 carácteres");
            } else {
                //Se llenan los datos de la ventana correspondiente.
                vlo_Producto.setVgc_Descripcion(txt_DetalleProducto.getText());
                vlo_Producto.setVgn_Precio(Double.parseDouble(txt_PrecioProducto.getText()));
                vlo_Producto.setVgn_idPorducto(Integer.parseInt(txt_idProducto.getText()));
            }
        }
        return vlo_Producto;
    }

    private ClsEntidadRetorno GuardarCliente() {
        //Variables
        ClsEntidadRetorno vlo_Retorno = new ClsEntidadRetorno();
        LogicaProducto vlo_logicaProducto = new LogicaProducto();

        //Inicio
        try {
            //Se invoca el metodo de guardar un cliente con l aentida dcorrespondiente.
            if (LeerDatos().getVgc_Descripcion().equals("") == false && LeerDatos().getVgc_Descripcion().length() <= 30) {
                vlo_Retorno = vlo_logicaProducto.GuardarProducto(LeerDatos());
            }
        } catch (Exception e) {
            throw e;
        }
        return vlo_Retorno;
    }

    private ClsEntidadRetorno Eliminar() {
        //Variables
        ClsEntidadRetorno vlo_retorno = new ClsEntidadRetorno();
        ClsEntidaProducto vlo_producto = new ClsEntidaProducto();
        LogicaProducto vlo_logicaProducto = new LogicaProducto();

        //Inicio
        try {
            //Se invova el metodo que lee los datos de la ventana.
            vlo_producto = LeerDatos();
            //Se invoca el metodo que elimina con el id del producto.
            vlo_retorno = vlo_logicaProducto.EliminarProducto(vlo_producto.getVgn_idPorducto());
        } catch (Exception e) {
            throw e;
        } finally {
            return vlo_retorno;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_DetalleProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_PrecioProducto = new javax.swing.JTextField();
        btn_Guardar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        txt_idProducto = new javax.swing.JTextField();
        btn_Salir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_Buscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Limpiar = new javax.swing.JButton();

        setTitle("Productos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Guardar Producto"));

        jLabel1.setText("Detalle:");

        jLabel2.setText("Precio: ₡");

        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/guardar.png"))); // NOI18N
        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/borrar.png"))); // NOI18N
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_DetalleProducto)
                    .addComponent(txt_PrecioProducto))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Guardar)
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_DetalleProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_PrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Eliminar)
                    .addComponent(btn_Guardar))
                .addContainerGap())
        );

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/salida.png"))); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));

        jLabel3.setText("Buscar producto:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/lupa.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/escoba.png"))); // NOI18N
        btn_Limpiar.setText("Limpiar");
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Salir))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salir)
                    .addComponent(btn_Limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        //Variables
        ClsEntidadRetorno vlo_retorno = new ClsEntidadRetorno();

        //Inicio
        try {
            vlo_retorno = GuardarCliente();
            if (vlo_retorno.getVgc_Mensaje().equals("") == false) {
                JOptionPane.showMessageDialog(this, vlo_retorno.getVgc_Mensaje());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Limpiar();
        CargarListaProductos();
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        //Variables
        ClsEntidadRetorno vlo_Retorno = new ClsEntidadRetorno();

        //Incio
        try {
            //txt_idProducto.setText("5");
            vlo_Retorno = Eliminar();

            JOptionPane.showMessageDialog(this, vlo_Retorno.getVgc_Mensaje());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Limpiar();
        CargarListaProductos();
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CargarListaProductos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //variables
        ClsEntidaProducto vlo_Producto = new ClsEntidaProducto();
        LogicaProducto vlo_LogicaProducto = new LogicaProducto();

        //Inicio
        if (evt.getClickCount() == 2) {
            try {
                int row = jTable1.rowAtPoint(evt.getPoint());
                vlo_Producto = vlo_LogicaProducto.ObtnerProducto(Integer.parseInt(jTable1.getValueAt(row, 0).toString()));
                if (vlo_Producto == null) {
                    JOptionPane.showMessageDialog(this, "Producto no encontrado en origen de datos.");
                    CargarListaProductos();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al tratar de cargar la información del producto.");
            }

            txt_DetalleProducto.setText(vlo_Producto.getVgc_Descripcion());
            txt_PrecioProducto.setText(Double.toString(vlo_Producto.getVgn_Precio()));
            txt_idProducto.setText(Integer.toString(vlo_Producto.getVgn_idPorducto()));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_Buscar;
    private javax.swing.JTextField txt_DetalleProducto;
    private javax.swing.JTextField txt_PrecioProducto;
    private javax.swing.JTextField txt_idProducto;
    // End of variables declaration//GEN-END:variables
}
