/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thomas
 */
import Entidades.ClsAngulos;
import Logica.LogicaAngulos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Entidades.ClsEntidadesTrigonometricas;

public class frmGradosRad extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;

        }
    };

    public frmGradosRad() {
        initComponents();
        this.closable = true;
        tblLista.setModel(modelo);
        modelo.addColumn("Grados");
        modelo.addColumn("Radianes π");
        modelo.addColumn("Sen");
        modelo.addColumn("Cos");
        modelo.addColumn("Tan");
    }

    private void AgregarValor(ClsAngulos pvo_Angulos) {
        //Variebles
        LogicaAngulos vlo_Logica = new LogicaAngulos();
        Object[] vlo_Objeto = new Object[5];
        ClsEntidadesTrigonometricas vlo_EntidadesTrigonometricas = new ClsEntidadesTrigonometricas();

        //Inicio
        try {
            vlo_EntidadesTrigonometricas = vlo_Logica.CalcularSCT(pvo_Angulos.getVgn_Radianes() * Math.PI);
        } catch (Exception e) {
            throw e;
        }
        vlo_Objeto[0] = pvo_Angulos.getVgn_Grados() + "°";
        vlo_Objeto[1] = pvo_Angulos.getVgn_Radianes() + "π";
        vlo_Objeto[2] = "Sin(" + String.format("%.1f", pvo_Angulos.getVgn_Grados()) + ")= " + String.format("%.1f", vlo_EntidadesTrigonometricas.getVgn_Seno());
        vlo_Objeto[3] = "Cos(" + String.format("%.1f", pvo_Angulos.getVgn_Grados()) + ")= " + String.format("%.1f", vlo_EntidadesTrigonometricas.getVgn_Coseno());
        vlo_Objeto[4] = "Tan(" + String.format("%.1f", pvo_Angulos.getVgn_Grados()) + ")= " + String.format("%.1f", vlo_EntidadesTrigonometricas.getVgn_Tangente());
        modelo.addRow(vlo_Objeto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        chkGrados = new javax.swing.JRadioButton();
        chkRadianes = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblPI = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Transformación Grados");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ángulos y Radianes"));

        chkGrados.setText("Grados a Radianes");
        chkGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGradosActionPerformed(evt);
            }
        });

        chkRadianes.setText("Radianes a Grados");
        chkRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRadianesActionPerformed(evt);
            }
        });

        jLabel1.setText("Medida:");

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });

        lblPI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pi-simbolo-de-constante-matematica (1).png"))); // NOI18N

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtResultado.setEditable(false);

        jLabel2.setText("Resultado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkGrados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkRadianes))
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtResultado)
                        .addGap(0, 0, 0))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(lblPI)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkGrados)
                    .addComponent(chkRadianes))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPI))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Lista de Resultados:");

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblLista);

        btnSalir.setText("Salir");

        btnLimpiar.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGradosActionPerformed
        //Se verifica si la opción se encuentra seleccionada
        if (chkGrados.isSelected()) {

            //Se deselcciona la opción contraria.
            chkRadianes.setSelected(false);
            lblPI.setVisible(false);
        }
    }//GEN-LAST:event_chkGradosActionPerformed

    private void chkRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRadianesActionPerformed
        //Se verifica si la opción se encuentra seleccionada
        if (chkRadianes.isSelected()) {
            //Se deselcciona la opción contraria.
            chkGrados.setSelected(false);
            lblPI.setVisible(true);
        }
    }//GEN-LAST:event_chkRadianesActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {
            txtResultado.setText(String.format("%.2f", LeerVariables()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al leer los valores.");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0' && c <= '9') || c == '.' || c == '-')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorKeyTyped

    private double LeerVariables() {
        //Variables
        ClsAngulos vlo_Angulos = new ClsAngulos();
        LogicaAngulos vlo_LogicaAngulos = new LogicaAngulos();
        //ClsEntidadesTrigonometricas vlo_Trigonometricas = new ClsEntidadesTrigonometricas();
        double vln_Resultado = 0;

        //Inicio
        try {
            if (!txtValor.getText().equals("")) {
                if ((chkGrados.isSelected()) && (chkRadianes.isSelected() == false)) {
                    //Se obtiene el valor de los campos ingresados por el usuario.
                    vlo_Angulos.setVgn_Grados(Double.parseDouble(txtValor.getText()));
                    vlo_Angulos.setVgn_Radianes(vlo_LogicaAngulos.GradosARadianes(vlo_Angulos.getVgn_Grados()));
                    vln_Resultado = vlo_Angulos.getVgn_Radianes();

                } else if ((chkRadianes.isSelected()) && (chkGrados.isSelected() == false)) {
                    //Se lee los datos de entrada escritos por el usuario.
                    vlo_Angulos.setVgn_Radianes(Double.parseDouble(txtValor.getText()));
                    vlo_Angulos.setVgn_Grados(vlo_LogicaAngulos.RadianesAGrados(vlo_Angulos.getVgn_Radianes()));
                    vln_Resultado = vlo_Angulos.getVgn_Grados();
                } else {
                    JOptionPane.showMessageDialog(this, "Error debe seleccionar algún tipo de conversión");
                    vln_Resultado = -1.111;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error se debe ingresar un valor númerico.");
                vln_Resultado = -1.111;
            }

            AgregarValor(vlo_Angulos);
        } catch (ArithmeticException ae) {
            vln_Resultado = -1.111;
            throw ae;
        } catch (Exception e) {
            throw e;
        } finally {
            return vln_Resultado;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGradosRad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGradosRad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGradosRad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGradosRad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGradosRad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chkGrados;
    private javax.swing.JRadioButton chkRadianes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPI;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
